from time import sleep
print("До паузы", end="")
print(" \u001b[36;1m           _-O#&&*''''?d:>b\\_")
print("          _O/'`''  '',, dMF9MMMMMMHo_")
print("       .o&#'        `'MbHMMMMMMMMMMMMHo.")
print("     .o'' '         vodM*$&&HMMMMMMMMMMM?.")
print("    ,'              $M&ood,~'`(&##MMMMMMH\\")
print("   /               ,MMMMMMM#b?#bobMMMMHMMML")
print("  &              ?MMMMMMMMMMMMMMMMM7MMM$R*Hk")
print(" ?$.            :MMMMMMMMMMMMMMMMMMM/HMMM|`*L")
print("|               |MMMMMMMMMMMMMMMMMMMMbMH'   T,")
print("$H#:            `*MMMMMMMMMMMMMMMMMMMMb#}'  `?")
print("]MMH#             ''*''''*#MMMMMMMMMMMMM'    -")
print("MMMMMb_                   |MMMMMMMMMMMP'     :")
print("HMMMMMMMHo                 `MMMMMMMMMT       .")
print("?MMMMMMMMP                  9MMMMMMMM}       -")
print("-?MMMMMMM                  |MMMMMMMMM?,d-    '")
print(" :|MMMMMM-                 `MMMMMMMT .M|.   :")
print("  .9MMM[                    &MMMMM*' `'    .")
print("   :9MMk                    `MMM#'        -")
print("     &M}                     `          .-")
print("        `&.                             .")
print("           `~,   .                    ./")
print("              . _                  .-PP")
print("                '`--._,dd###pp='''")
sleep(0.3)
print("\u001b[50A" , end="")
print('\033[2J', end="") # очистит экран
print("После паузы")
print(" \u001b[36;1m            .ovr:HMM#?:`' >b\\_")
print("          .,:&Hi' `'   '' \\\\|&bSMHo_")
print("        oHMMM#*}          `?&dMMMMMMHo.")
print("     .dMMMH'''''           ,oHH*&&9MMMM?.")
print("    ,MMM*'                 `*M\\bd<|'*&#MH\\")
print("   dHH?'                   :MMMMMM#bd#odMML")
print("  H' |\\                  `dMMMMMMMMMMMMMM9Mk")
print(" JL/'7+,.                `MMMMMMMMMMMMMMMH9ML")
print("-`Hp     '               |MMMMMMMMMMMMMMMMHH|:")
print(":  \\\\#M#d?                `HMMMMMMMMMMMMMMMMH.")
print(".   JMMMMM##,              ``*''''*#MMMMMMMMH")
print("-. ,MMMMMMMM6o_                    |MMMMMMMM':")
print(":  |MMMMMMMMMMMMMb\\                 TMMMMMMT :")
print(".   ?MMMMMMMMMMMMM'                 :MMMMMM|.`")
print("-    ?HMMMMMMMMMM:                  HMMMMMM\\|:")
print(" :     9MMMMMMMMH'                 `MMMMMP.P.")
print("  .    `MMMMMMT''                   HMMM*''-")
print("   -    TMMMMM'                     MM*'  -")
print("    '.   HMM#                            -")
print("      -. `9M:                          .'")
print("        -. `b,,    .                . '")
print("          '-\\   .,               .-`")
print("             '-:b~\\\\_,oddq==--'")
sleep(0.3)
print("\u001b[60A" , end="")
print('\033[2J', end="") # очистит экран
print("После паузы-2")
print(" \u001b[36;1m              _oo##'9MMHb':'-,o_")
print("          .vM':HH$'    '''  '' -\\7*_")
print("       .oHMMMHMH#9:          '\\bMMMMHo.")
print("     . ,dMMMMMMMMMMM'`' `           ?MP?.")
print("    . |MMMMMMMMMMM'                 `'$b&\\")
print("   -  |MMMMHH##M'                     HMMH?")
print("  -   TTMM|    >..                   \\MMMMMH")
print(" :     |MM\\,#-''$~b\\.                `MMMMMM+")
print(".       ``'H&#        -               &MMMMMM|")
print(":            *\\v,#MHddc.              `9MMMMMb")
print(".               MMMMMMMM##\\             `'':HM")
print("-          .  .HMMMMMMMMMMRo_.              |M")
print(":             |MMMMMMMMMMMMMMMM#\\           :M")
print("-              `HMMMMMMMMMMMMMMM'           |T")
print(":               `*HMMMMMMMMMMMM'            H'")
print(" :                 MMMMMMMMMMM|            |T")
print("  .                MMMMMMMM?'             ./")
print("  `.               MMMMMMH'              ./")
print("    -.            |MMMH#'                .")
print("      .           `MM*                . '")
print("        -.         #M: .    .       .-")
print("          ` .         .,         .-")
print("              '-.-~ooHH__,,v~--`")
print("\u001b[0m END")


